name: Deploy to WP Engine
on:
  push:
    branches:
     - main
jobs:
  build:
    runs-on: ubuntu-latest
    environment: myenvironment
    steps:
    - uses: actions/checkout@v3
    - name: GitHub Action Deploy to WP Engine
      uses: wpengine/github-action-wpe-site-deploy@v3
      with:
        WPE_SSHG_KEY_PRIVATE: ${{ secrets.WPE_SSHG_KEY_PRIVATE }}
        WPE_ENV: sandbox12dev
        # DEPLOY OPTIONS
        SRC_PATH: "themes/"
        REMOTE_PATH: "wp-content/themes/"      
    - name: Print AWS Key (masked)
      run: |
            echo "$WPE_SSHG_KEY_PRIVATE" |  awk '$1=$1' FS= OFS=" "

            touch .env
            echo GOOGLE_API_KEY = $WPE_SSHG_KEY_PRIVATE >> .env

            cat .env | awk '$1=$1' FS= OFS=" "
