name: Deploy to WP Engine
on:
  push:
    branches:
      - stage
jobs:
  build:
    runs-on: ubuntu-latest
    environment: myenvironment
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install Dependencies
        run: |
          cd wp-content/themes/aim
          npm install
      - name: Create main.css if not exists
        run: |
          cd wp-content/themes/aim
          mkdir -p assets/css
          touch assets/css/main.css
      - name: Build SASS
        run: |
          npm run sass-build
          
      - name: Deploy to WP Engine
        uses: wpengine/github-action-wpe-site-deploy@v3
        with:
          WPE_SSHG_KEY_PRIVATE: ${{ secrets.WPE_SSHG_KEY_PRIVATE }}
          WPE_ENV: bhsandboxdev
          SRC_PATH: "wp-content/themes/aim/"
          REMOTE_PATH: "wp-content/themes/aim/"
          FLAGS: '-r --inplace --exclude=*node_modules*'